<a href="https://colab.research.google.com/github/niafthomas/niafthomas.github.io/blob/main/EuropeKepler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests, json, pandas as pd

In [2]:
import numpy as np

In [3]:
topo=requests.get('https://raw.githubusercontent.com/deldersveld/topojson/master/continents/europe.json').json()

In [4]:
for i in topo['objects']['continent_Europe_subunits']['geometries']:
  print(i['properties']['geounit'])

Albania
Aland
Andorra
Austria
BrusselsCapitalRegion
FlemishRegion
Bulgaria
BosniaandHerzegovina
RepublicSrpska
Belarus
WalloonRegion
Switzerland
CzechRepublic
Germany
Denmark
Denmark
England
Estonia
Spain
Finland
FaroeIslands
France
Guernsey
Guernsey
Guernsey
Gibraltar
Greece
Croatia
Hungary
IsleofMan
Ireland
Iceland
Italy
Italy
Italy
Jersey
Kosovo
Liechtenstein
Lithuania
Luxembourg
Latvia
Monaco
Moldova
Macedonia
Malta
Montenegro
NorthernIreland
JanMayen
Netherlands
Norway
Svalbard
Poland
Portugal
Romania
Russia
Russia
Scotland
SanMarino
Serbia
Vojvodina
Slovakia
Slovenia
Sweden
Ukraine
Vatican
Wales

Bringing in the social mobility and home ownership data from World Economic Forum and Wikipedia to match it to the country names. (Previously scraped this data)

In [6]:
data=pd.read_csv('https://raw.githubusercontent.com/niafthomas/niafthomas.github.io/main/Project/Data/Europe_HomeO_SM.csv').set_index('Country')

In [7]:
data

                Home ownership rate(%)  Index Score
Country
Russia                            89.0         64.7
France                            64.1         76.7
Spain                             76.2         70.0
Sweden                            64.5         83.5
Norway                            80.3         83.6
Germany                           51.1         78.8
Finland                           70.7         83.6
Poland                            84.2         69.1
Italy                             72.4         67.4
United Kingdom                    63.0         74.4
Romania                           96.1         63.1
Greece                            74.6         59.8
Bulgaria                          84.3         63.8
Iceland                           73.6         82.7
Hungary                           91.3         65.8
Portugal                          73.9         72.0
Austria                           55.3         80.1
Czech Republic                    78.6         74.7
Serbia                            83.3         63.8
Ireland                           68.7         75.0
Lithuania                         90.3         70.5
Latvia                            80.2         69.0
Croatia                           89.7         66.7
Slovakia                          90.9         68.5
Estonia                           81.4         73.5
Denmark                           60.8         85.2
Switzerland                       41.6         82.1
Netherlands                       69.0         82.4
Belgium                           72.3         80.1
Turkey                            58.8         51.3
Slovenia                          74.6         76.4
Luxembourg                        70.9         79.8
Malta                             79.8         75.0
Cyprus                            67.9         69.4

In [8]:
colour_code = [1,2,3,4,5,6,7,8,9]

In [12]:
# conditions to assign colour value based on combination of rate of home ownership and social mobility
conditions = [
    (data['Home ownership rate(%)'] < 68) & (data['Index Score'] < 69),
    (data['Home ownership rate(%)'] < 68) & (data['Index Score'] > 69) & (data['Index Score'] < 76),
    (data['Home ownership rate(%)'] < 68) & (data['Index Score'] > 76),
    (data['Home ownership rate(%)'] > 68) & (data['Home ownership rate(%)'] < 80) & (data['Index Score'] < 69),
    (data['Home ownership rate(%)'] > 68) & (data['Home ownership rate(%)'] < 80) & (data['Index Score'] > 69) & (data['Index Score'] < 76),
    (data['Home ownership rate(%)'] > 68) & (data['Home ownership rate(%)'] < 80) & (data['Index Score'] > 76),
    (data['Home ownership rate(%)'] > 68) & (data['Index Score'] < 59),
    (data['Home ownership rate(%)'] > 68) & (data['Index Score'] > 59) & (data['Index Score'] < 76),
    (data['Home ownership rate(%)'] > 68) & (data['Index Score'] > 76)
    ]

In [13]:
# create a list of the values we want to assign for each condition
colour_code = [1,2,3,4,5,6,7,8,9]

# create a new column and use np.select to assign values to it using our lists as arguments
data["Colour"] = np.select(conditions, colour_code)

In [14]:
data["Colour"] = np.select(conditions, colour_code)
data

                Home ownership rate(%)  Index Score  Colour
Country
Russia                            89.0         64.7       8
France                            64.1         76.7       3
Spain                             76.2         70.0       5
Sweden                            64.5         83.5       3
Norway                            80.3         83.6       9
Germany                           51.1         78.8       3
Finland                           70.7         83.6       6
Poland                            84.2         69.1       8
Italy                             72.4         67.4       4
United Kingdom                    63.0         74.4       2
Romania                           96.1         63.1       8
Greece                            74.6         59.8       4
Bulgaria                          84.3         63.8       8
Iceland                           73.6         82.7       6
Hungary                           91.3         65.8       8
Portugal                          73.9         72.0       5
Austria                           55.3         80.1       3
Czech Republic                    78.6         74.7       5
Serbia                            83.3         63.8       8
Ireland                           68.7         75.0       5
Lithuania                         90.3         70.5       8
Latvia                            80.2         69.0       8
Croatia                           89.7         66.7       8
Slovakia                          90.9         68.5       8
Estonia                           81.4         73.5       8
Denmark                           60.8         85.2       3
Switzerland                       41.6         82.1       3
Netherlands                       69.0         82.4       6
Belgium                           72.3         80.1       6
Turkey                            58.8         51.3       1
Slovenia                          74.6         76.4       6
Luxembourg                        70.9         79.8       6
Malta                             79.8         75.0       5
Cyprus                            67.9         69.4       2

We extend the topojson properties

In [16]:
for i in topo['objects']['continent_Europe_subunits']['geometries']:
  country=i['properties']['geounit']
  if country in data.index:
    print(country,'found! Extending data..')
    i['properties']['Scoial Mobility Score']=data.loc[country]['Index Score']
    i['properties']['Home Ownership Rate (%)']=data.loc[country]['Home ownership rate(%)']
    i['properties']['Colour']=data.loc[country]['Colour']

Austria found! Extending data..
Bulgaria found! Extending data..
Switzerland found! Extending data..
Germany found! Extending data..
Denmark found! Extending data..
Denmark found! Extending data..
Estonia found! Extending data..
Spain found! Extending data..
Finland found! Extending data..
France found! Extending data..
Greece found! Extending data..
Croatia found! Extending data..
Hungary found! Extending data..
Ireland found! Extending data..
Iceland found! Extending data..
Italy found! Extending data..
Italy found! Extending data..
Italy found! Extending data..
Lithuania found! Extending data..
Luxembourg found! Extending data..
Latvia found! Extending data..
Malta found! Extending data..
Netherlands found! Extending data..
Norway found! Extending data..
Poland found! Extending data..
Portugal found! Extending data..
Romania found! Extending data..
Russia found! Extending data..
Russia found! Extending data..
Serbia found! Extending data..
Slovakia found! Extending data..
Slovenia found! Extending data..
Sweden found! Extending data..

In [17]:
topo['objects']['continent_Europe_subunits']['geometries'][3]['properties']

{'Colour': 3.0,
 'Home Ownership Rate (%)': 55.3,
 'Scoial Mobility Score': 80.1,
 'geounit': 'Austria',
 'type': 'Sovereigncountry'}

In [18]:
import json
open('topojson_export_europe.json','w').write(json.dumps(topo))

33932